---
title: "Reading environment from a file"
author: "Jaideep Joshi"
date: "28 March 2022"
output: html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F, echo = F}
library(fisheRy)
source("../tests/ref/parameters.cod.R")
source("../tests/ref/simulator.7.R")
```

### Create a population


```{r}
params_file = "../params/cod_params.ini"
```

```{r }
fish = new(Fish, params_file)
fish$par$flag = 1
fish$par$Bhalf = 3.65e8
# fish$par$s0 = 0.0445
fish$par$growth_model_name = "Dankel22"
fish$par$maturation_model_name = "Dankel22"
fish$par$mortality_model_name = "Dankel22"
fish$par$recruitment_model_name = "BevertonHoltDirect"
fish$init(1.93e3, 5.61)

pop = new(Population, fish)
```

### Read environment from a file


```{r}
pop$readEnvironmentFile("../params/environment.csv")

dat = read.csv("../params/environment.csv")

tvec = 1977:2017
Rvec = numeric(length(tvec))
Tvec = numeric(length(tvec))
for (i in 1:length(tvec)){
  pop$updateEnv(tvec[i])
  Rvec[i] = pop$env$recruitment_noise_multiplier
  Tvec[i] = pop$env$temperature
}

par(mfrow=c(2,1), mar=c(4,4,1,1))
plot(Rvec~tvec, type="l")
points(dat$R.multiplier~dat$year, col="blue")
plot(Tvec~tvec, type="l")
points(dat$FBT~dat$year, col="blue")

```


```{r}
tvec = 1877:2100
Rvec = numeric(length(tvec))
Tvec = numeric(length(tvec))
for (i in 1:length(tvec)){
  pop$updateEnv(tvec[i])
  Rvec[i] = pop$env$recruitment_noise_multiplier
  Tvec[i] = pop$env$temperature
}

par(mfrow=c(2,1), mar=c(4,4,1,1))
plot(Rvec~tvec, type="l")
points(dat$R.multiplier~dat$year, col="blue")
plot(Tvec~tvec, type="l")
points(dat$FBT~dat$year, col="blue")
```


```{r}
pop$updateEnv(1976)
```
