---
title: "Safe operating spaces"
author: "Jaideep Joshi"
date: "28 March 2022"
output: html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F, echo = F}
library(rfish)
library(tidyverse)
source("../tests/ref/parameters.cod.R")
source("../tests/ref/simulator.7.R")
```


```{r}
# Create a prototype fish as usual
fish = new(Fish)
# All old parameters But new growth model
fish$par$use_old_model_mor = F
fish$par$use_old_model_mat = F
fish$par$use_old_model_fec = F
fish$par$growth_model = 1

par = c(0.08094733, 187837572, 148.6918)
fish$par$s0 = par[1] #0.07
fish$par$Bhalf = par[2] #2.65e8
fish$par$pmrn_lp50 = par[3] #118.122779*1.15

sim = new(Simulator, fish)
sim$equilibriateNaturalPopulation(1.93e3, 5.61, 2e6)
```

```{r}
plot_timeseries = function(res_ibm, pop, h, nsteps=200){
  
  d = pop$get_state()
  table(d$age)
  par(mfrow = c(4,3), mar=c(4,4,1,1))
  
  plot(y=res_ibm$ssb/1e9, x=seq(1,nsteps,1), ylab="SSB (MT)", xlab="Year", col="cyan3", type="l")
  
  plot(y=res_ibm$yield/1e9, x=seq(1,nsteps,1), ylab="Yield (MT)", xlab="Year", col="cyan3", type="l")
  
  plot(y=res_ibm$employment.sea, x=seq(1,nsteps,1), ylab="Employment at sea (person-years)", xlab="Year", col="cyan3", type="l")
  
  plot(y=res_ibm$employment.shore, x=seq(1,nsteps,1), ylab="Employment on shore (person-years)", xlab="Year", col="cyan3", type="l")
  
  plot(y=res_ibm$profit.sea/1e9, x=seq(1,nsteps,1), ylab="Profit at sea (Billions NOK)", xlab="Year", col="cyan3", type="l")
  
  plot(y=res_ibm$profit.shore/1e9, x=seq(1,nsteps,1), ylab="Profit at shore (Billions NOK)", xlab="Year", col="cyan3", type="l")
  
  d = pop$get_state()
  d1 = d %>% group_by(age) %>% summarize(mat = length(which(isMature))/length(isMature))
  plot(mat, type="l")
  points(d1$mat~I(d1$age-1), type="o", col="cyan3") # Decrement age to get the right maturation prob (see note above)
  
    plot(res_ibm$r0~seq(1,nsteps,1), xlab="Year", ylab= "r0", col="cyan3", type="p", ylim=c(0,30))
    abline(h=21.77, col="black")

    matplot(y=cbind(res_ibm$survival_mean, res_ibm$maturity, res_ibm$Nrel), x=seq(1,nsteps,1), xlab="Year", ylab= "p_survival / maturity / Nrel", col=c("cyan3", "magenta3", "yellow3"), type="l", lty=1, ylim=c(0,1.2))
    
  matplot(y=cbind(res_ibm$factor_dg, res_ibm$factor_dr), x=seq(1,nsteps,1), xlab="Year", ylab= "dl_ratio, r_ratio", col=c("cyan3", "magenta3"), type="l", lty=1)

  matplot(y=cbind(res_ibm$length90, res_ibm$max_length), x=seq(1,nsteps,1), xlab="Year", ylab= "Length (90 %ile)", col=c("cyan3", "cyan4"), type="l", lty=1)
  
  dist = table(d$age, d$length)
  image(x=as.numeric(rownames(dist)), y = as.numeric(colnames(dist)), z=log(1+3*log(dist)), col=scales::viridis_pal()(100), xlab="Age", ylab="Length")
}
```


Simulate a status quo population with 
$h = 0.41$, $L50 = 45$, $T = 5.6$.

```{r}
pop_sq = new(Population, fish)
pop_sq$set_superFishSize(1e6)

h_sq = 0.05
lf_sq = 45
t_sq = 5.6
nsteps_sq = 500
res_ibm_sq = sim$simulate(pop_sq, lf_sq, h_sq, nsteps_sq, 1.93e3, t_sq, T)

plot_timeseries(res_ibm_sq, pop_sq, h_sq, nsteps_sq)
```

Continue population under different conditions

```{r}
nsteps = 50
h = 0.2
lf = 45

pop1 = pop_sq ## NO! This creates a shallow copy
res_ibm = sim$simulate(pop1, lf, h, nsteps, 1.93e3, 5.61, F)

plot_timeseries(res_ibm, pop1, h, nsteps)

utils = cbind(res_ibm$ssb/max(res_ibm$ssb), res_ibm$yield/max(res_ibm$yield), res_ibm$employment/max(res_ibm$employment), res_ibm$profit/max(res_ibm$profit))

par(mfrow=c(1,1), mar=c(4,4,1,1))
matplot(y=utils, x=1:50, xlab="Years", ylab="Utilities", col=c("darkgreen", "darkgoldenrod1", "dodgerblue3", "coral1"), lty=1, lwd=2, type="l")
```

Thus, we can plot the two populations together:

```{r}
plot(c(res_ibm_sq$ssb, res_ibm$ssb)~seq(1,550), type="l", col="cyan3")
```

### Multiple populations


```{r}
plot_hscan = function(res_ibm_full, nsteps=200){
  lf = 45
  arr = res_ibm_full 
  names = c("ssb", "yield", "emp", "profit", "emp.sea", "emp.shr", 
	                           "profit.sea", "profit.shr", "tsb", 
	                           "r0", "nrecruits", "nsuperfish",
	                           "factor_dg", "factor_dr", "max_length",
                             "length90", "p_survival", "maturity", "Nrel")
  dat_ibm = data.frame(matrix(ncol=length(names), nrow=0))
  colnames(dat_ibm) = names
  dat = data.frame(matrix(ncol=7, nrow=0))
  colnames(dat) = c("ssb", "yield", "emp.sea", "emp.shr", "profit.sea", "profit.shr", "tsb")
  for (ih in 1:length(hvec)){
    v_ibm = colMeans(arr[, ih, 1, 1,])
    dat_ibm[nrow(dat_ibm)+1,] = v_ibm/c(1e9, 1e9, 1,1, 1, 1, 1e9, 1e9, 1e9, 1, 1, 1, 1, 1,1,1,1,1,1)
  }
  # dat$employment = dat$emp.sea+dat$emp.shr
  # dat$profit = dat$profit.sea+dat$profit.shr
  
  
  par(mfrow = c(4,3), mar=c(5,5,1,1), cex.lab=1.5, cex.axis=1.5)
  matplot(ylab="ssb (MT)",y=cbind(dat_ibm$ssb), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="tsb (MT)",y=cbind(dat_ibm$tsb), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="yield (MT)",y=cbind(dat_ibm$yield), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="employment sea (PY)",y=cbind(dat_ibm$emp.sea), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="employment shore (PY)",y=cbind(dat_ibm$emp.shr), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="profit sea (Bn NOK)",y=cbind(dat_ibm$profit.sea), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="profit shore (Bn NOK)",y=cbind(dat_ibm$profit.shr), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="Length %iles",y=cbind(dat_ibm$max_length, dat_ibm$length90), x=hvec, type="l", col=c("cyan2", "cyan4"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="dl ratio, r ratio",y=cbind(dat_ibm$factor_dg, dat_ibm$factor_dr), x=hvec, type="l", col=c("cyan3", "magenta3"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="Superfish",y=cbind(dat_ibm$nsuperfish), x=hvec, type="l", col=c("cyan2", "cyan4"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="Survival prob / Maturity",y=cbind(dat_ibm$p_survival, dat_ibm$maturity), x=hvec, type="l", col=c("cyan3", "magenta3"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="Survival prob / Maturity / Nrel",y=cbind(dat_ibm$p_survival, dat_ibm$maturity, dat_ibm$Nrel), x=hvec, type="l", col=c("cyan3", "magenta3", "yellow3"), lwd=1, lty=1, xlab="Harvest prop")
  }

```

```{r fig.height=9}
# pop$par$dsea = 0.054
nsteps=50
hvec = seq(0., 0.99, length.out=25)
pop = pop_sq
pop$set_superFishSize(5e5)
res_ibm_full = sim$simulate_multi_2d(pop, c(5.6), lf, hvec, nsteps, 1.93e3, F)
save(res_ibm_full, file = "res_ibm_h.Rdata")

plot_hscan(res_ibm_full, nsteps)
```

<!-- ```{r} -->
<!-- # pop$par$dsea = 0.054 -->
<!-- nsteps=50 -->
<!-- hvec = seq(0., 0.7, length.out=20) -->
<!-- pop1 = pop_sq -->
<!-- pop1$set_superFishSize(5e5) -->
<!-- res_ibm_full = sim$simulate_multi_2d(pop1, c(5.6), lf, hvec, nsteps, 1.93e3, F) -->

<!-- plot_hscan(res_ibm_full, nsteps) -->
<!-- ``` -->

### Utilties

```{r fig.height=3}
arr = res_ibm_full[,,,,1:4]

lfvec = c(lf)
d = sim$max_avg_utils_2d(c(4,1, length(lfvec),length(hvec),50), arr)

utils = array(data=d, dim=c(length(hvec),length(lfvec),1, 4))

par(mfrow=c(1,2), mar=c(4,4,1,1))
matplot(y=matrix(data=d, ncol=4), x=hvec, lty=1, type="l", col=c("darkgreen", "darkgoldenrod1", "dodgerblue3", "coral1"), lwd=3, ylim=c(0,1))
abline(h=0, col="grey")
plot(1,1, cex=0.01, xlab = "", ylab = "", axes = F)
legend(x = 0.7, y = 1, legend = c("ssb", "yield", "employment", "profit"), fill = c("darkgreen", "darkgoldenrod1", "dodgerblue3", "coral1"))


```

### JSS

```{r fig.height=3}
arr = res_ibm_full[,,,,1:4]

lfvec = c(lf)
ss = sim$stakeholder_satisfaction_2d(c(4,1, length(lfvec),length(hvec),50), arr)

par(mfrow=c(1,2), mar=c(4,4,1,1))
matplot(y=matrix(data=ss, ncol=5), x=hvec, lty=1, type="l", lwd=3, ylim=c(0,1), col=c("grey", "darkgoldenrod1", "dodgerblue3", "coral1","darkgreen"))
abline(h=0, col="grey")
plot(1,1, cex=0.01, xlab = "", ylab = "", axes = F)
legend(x = 0.7, y = 1, legend = c("Industrial", "Artisanal", "Emp. policymakers", "Profit. policymakers", "Conservationists"), fill=c("grey", "darkgoldenrod1", "dodgerblue3", "coral1","darkgreen"))
```


```{r fig.height=3}
mat = matrix(data=ss, ncol=5)
JSS_min = apply(mat, 1, min)
JSS_mean = apply(mat, 1, mean)
JSS_hmean = 1/apply(1/mat, 1, mean)

par(mfrow=c(1,2), mar=c(4,4,1,1))
matplot(y=cbind(JSS_mean, JSS_hmean, JSS_min), x=hvec, lty=1, type="l", lwd=3, ylim=c(0,1), col=c("darkgoldenrod1", "dodgerblue3", "darkgreen"))
plot(1,1, cex=0.01, xlab = "", ylab = "", axes = F, ylim=c(0,1))
legend(x = 0.7, y = 1, legend = c("Mean", "Harmonic mean", "Min"), fill=c("darkgoldenrod1", "dodgerblue3","darkgreen"))

```
