---
title: "Model calibration"
author: "Jaideep Joshi"
date: "28 March 2022"
output: html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F, echo = F}
library(fisheRy)
library(tidyverse)
source("../tests/ref/parameters.cod.R")
source("../tests/ref/simulator.7.R")
```

```{r}
datraw = read.csv("~/Documents/fish_project/growth_model_calib_data/environmental.csv")
dat = datraw %>% filter(year >= 1978 & year <= 2005)
```

```{r}
params_file = "../params/cod_params.ini"
```


```{r}
plot_timeseries = function(res_ibm, pop, h, max_nx=100){
  res = simulate(h, lf, F)
  
  d = pop$get_state()
  table(d$age)
  par(mfrow = c(2,3), mar=c(4,4,1,1))
  
  nyears = nrow(res_ibm)
  dat_t = (nyears-nrow(dat)+1) : nyears
  nsteps = min(nrow(res_ibm), max_nx)
  dat_i = (nrow(res_ibm)-nsteps+1) : nrow(res_ibm)
  
  res_ibm = res_ibm[dat_i,]
    
  ssb.max = max(c(res_ibm$ssb/1e9, res$summaries$SSB/1e9, dat$ssb*1e3/1e9), na.rm = T)
  plot(y=res_ibm$ssb/1e9, x=dat_i, ylab="SSB (MT)", xlab="Year", col="cyan3", type="l", ylim=c(0,ssb.max))
  points(y=res$summaries$SSB/1e9, x=res$summaries$year, type="l")
  points(y=dat$ssb*1e3/1e9, x=dat_t, col="green", type="o", lwd=0.4)

  tsb.max = max(c(res_ibm$tsb/1e9, res$summaries$TSB/1e9, dat$totb*1e3/1e9), na.rm=T)
  plot(y=res_ibm$tsb/1e9, x=dat_i, ylab="TSB (MT)", xlab="Year", col="cyan3", type="l", ylim=c(0,tsb.max))
  points(y=res$summaries$TSB/1e9, x=res$summaries$year, type="l")
  points(y=dat$totb*1e3/1e9, x=dat_t, col="green", type="o", lwd=0.4)

  yield.max = max(c(res_ibm$yield/1e9, res$summaries$Y/1e9))
  plot(y=res_ibm$yield/1e9, x=dat_i, ylab="Yield (MT)", xlab="Year", col="cyan3", type="l", ylim=c(0,yield.max))
  points(y=res$summaries$Y/1e9, x=res$summaries$year, type="l")
  points(y=dat$catch*1e3/1e9, x=dat_t, col="green", type="o", lwd=0.4)

  nr.max = max(c(res_ibm$nfish_ra/1e6), dat$recr*1e3/1e6, na.rm=T)
  plot(y=res_ibm$nfish_ra/1e6, x=dat_i, ylab="Recruits (Mn)", xlab="Year", col="cyan3", type="l", ylim=c(0,nr.max))
  points(y=dat$recr*1e3/1e6, x=dat_t, col="green", type="o", lwd=0.4)

  d = pop$get_state()
  d1 = d %>% group_by(age) %>% summarize(mat = length(which(isMature))/length(isMature))
  plot(mat, type="l")
  points(d1$mat~I(d1$age-1), type="o", col="cyan3", xlab = "age") # Decrement age to get the right maturation prob (see note above)
}

```

```{r}
# Create a prototype fish as usual
fish = new(Fish, params_file)
fish$par$s0 = 0.1 #0.02
# fish$par$M0 = 0.05 #0.02
# fish$par$Bhalf = 5.3e8
# fish$par$pmrn_lp50 = 118.122779

sim = new(Simulator, fish)

sim$equilibriateNaturalPopulation(1.93e3, 5.61, 10e6)

pop = new(Population, fish)
#pop$par$dsea = 0.09 # tuned value
pop$set_superFishSize(10e6)

nsteps = 200
h = 1-exp(-mean(dat$F))
lf = 45

pop$verbose = F
res_ibm = sim$simulate(pop, lf, h, nsteps, 1.93e3, 5.61, T)

plot_timeseries(res_ibm, pop, h, 200)
```

```{r}
error_fun = function(par, nsup = 10e6, bplot=F, nymax=50){

  fish = new(Fish, params_file)
  fish$par$s0 = par[1] #0.07
  #fish$par$pmrn_lp50 = par[2] #118.122779*1.15
  # fish$par$M0 = par[2] #118.122779*1.15
  
  sim = new(Simulator, fish)
  
  sim$equilibriateNaturalPopulation(1.93e3, 5.61, nsup)
  
  pop = new(Population, fish)
  #pop$par$dsea = 0.09 # tuned value
  pop$set_superFishSize(nsup)
  
  nsteps = 500
  h = 1-exp(-mean(dat$F))
  lf = 45
  
  pop$verbose = F
  res_ibm = sim$simulate(pop, lf, h, nsteps, 1.93e3, 5.61, T)
  
  obs = numeric(4)
  obs[1] = mean((dat$ssb*1e3/1e9), na.rm=T)  # MT
  obs[2] = mean((dat$totb*1e3/1e9), na.rm=T) # MT
  obs[3] = mean((dat$catch*1e3/1e9), na.rm=T) # MT
  obs[4] = mean((dat$recr*1e3/1e9), na.rm=T) # recruits in billions
  
  pred = numeric(4)
  ids = (nsteps-nrow(dat)+1):nsteps
  pred[1] = mean((res_ibm$ssb[ids]/1e9), na.rm=T)
  pred[2] = mean((res_ibm$tsb[ids]/1e9), na.rm=T)
  pred[3] = mean((res_ibm$yield[ids]/1e9), na.rm=T)
  pred[4] = mean((res_ibm$nfish_ra[ids]/1e9), na.rm=T)

  weights = c(1,0,1,1)
  err_partial = weights * log(pred/obs)^2
  err = sum(err_partial)

  nrep=5
  ids1 = (nsteps-nrow(dat)*nrep+1):nsteps
  pred1 = (res_ibm[ids1,] %>% select(ssb, tsb, yield, nfish_ra))/1e9
  obs1 = (dat %>% select(ssb, totb, catch, recr))[rep(seq(1,nrow(dat)),nrep),]*1e3/1e9
  
  err1 = sum((pred1-obs1)^2)
    
  cat("par = ", par, " | ", obs, " / ", pred, " | ", err_partial, " | ", err, " |", err1, "\n")
  
  if (bplot) {
    plot_timeseries(res_ibm, pop, h, nymax)

    par(mfrow=c(1,2), mar=c(4,4,4,1), oma=c(1,1,1,1))
    cols = c("darkgreen", "darkgoldenrod1", "dodgerblue3", "coral1")
    plot(obs~pred, ylim=c(0, max(c(obs,pred))), xlim=c(0, max(c(obs,pred))), col=cols, pch=20, cex=2, cex.lab=1.2, ylab="Observed", xlab="Predicted")
    abline(0,1, col="grey")
    plot(1,NA, cex=0.01, xlab = "", ylab = "", axes = F, ylim=c(0,1))
    legend(x = 0.6, y = 0.9, legend = c("Spawning stock biomass", "Total stock biomass", "Yield", "Recruitment"), col = cols, pch=20, cex=1.1)
    
    par(mfrow=c(2,2), mar=c(4,4,4,1), oma=c(1,1,1,1))
    for(k in 1:4){
      ymax = max(c(pred1[,k], obs1[,k]))
      plot(obs1[,k]~pred1[,k], col="green3", main=c("ssb","tsb","yield","recr")[k], xlim=c(0,ymax), ylim=c(0,ymax))
      abline(0,1, col="black")
    }
    abline(0,1,col="grey")
  }
  
  err
}


error_fun(par=c(0.05945035), nsup=5e6, bplot=T)
```

Optimize
  
```{r}
opt = optim(par = c(0.058), fn = error_fun, ns = 10e6, control=list(parscale=c(0.08), maxit=50)) #, method = "Brent", lower=0.00000001, upper=0.2)
print(opt)
```

```{r}
error_fun(opt$par, ns=5e6, bplot=T)
```


