---
title: "Simulating a fished population"
author: "Jaideep Joshi"
date: "28 March 2022"
output: html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F, echo = F}
library(fisheRy)
library(tidyverse)
source("../tests/ref/parameters.cod.R")
source("../tests/ref/simulator.7.R")
```


```{r}
# Create a prototype fish as usual
fish = new(Fish)
# All old parameters But new growth model
fish$par$use_old_model_mor = F
fish$par$use_old_model_mat = F
fish$par$use_old_model_fec = F
fish$par$growth_model = 1

par = c(0.08094733, 187837572, 148.6918)
fish$par$s0 = par[1] #0.07
fish$par$Bhalf = par[2] #2.65e8
fish$par$pmrn_lp50 = par[3] #118.122779*1.15

sim = new(Simulator, fish)
sim$equilibriateNaturalPopulation(1.93e3, 5.61, 10e6)
```



```{r}
plot_timeseries = function(res_ibm, pop, h){
  res = simulate(h, lf, F)
  
  d = pop$get_state()
  table(d$age)
  par(mfrow = c(4,3), mar=c(4,4,1,1))
  
  ssb.max = max(c(res_ibm$ssb/1e9, res$summaries$SSB/1e9))
  plot(y=res_ibm$ssb/1e9, x=seq(1,nsteps,1), ylab="SSB (MT)", xlab="Year", col="cyan3", type="l", ylim=c(0,ssb.max))
  points(y=res$summaries$SSB/1e9, x=res$summaries$year, type="l")
  
  yield.max = max(c(res_ibm$yield/1e9, res$summaries$Y/1e9))
  plot(y=res_ibm$yield/1e9, x=seq(1,nsteps,1), ylab="Yield (MT)", xlab="Year", col="cyan3", type="l", ylim=c(0,yield.max))
  points(y=res$summaries$Y/1e9, x=res$summaries$year, type="l")
  
  emp.max = max(c(res_ibm$employment.sea, res$summaries$D.sea))
  plot(y=res_ibm$employment.sea, x=seq(1,nsteps,1), ylab="Employment at sea (person-years)", xlab="Year", col="cyan3", type="l", ylim=c(0,emp.max))
  points(y=res$summaries$D.sea, x=res$summaries$year, type="l")
  
  emp.max = max(c(res_ibm$employment.shore, res$summaries$D.shr))
  plot(y=res_ibm$employment.shore, x=seq(1,nsteps,1), ylab="Employment on shore (person-years)", xlab="Year", col="cyan3", type="l", ylim=c(0,emp.max))
  points(y=res$summaries$D.shr, x=res$summaries$year, type="l")
  
  p.sea.max = max(c(res_ibm$profit.sea/1e9, res$summaries$P.sea/1e9))
  p.sea.min = min(c(res_ibm$profit.sea/1e9, res$summaries$P.sea/1e9))
  plot(y=res_ibm$profit.sea/1e9, x=seq(1,nsteps,1), ylab="Profit at sea (Billions NOK)", xlab="Year", col="cyan3", type="l", ylim=c(p.sea.min,p.sea.max))
  points(y=res$summaries$P.sea/1e9, x=res$summaries$year, type="l")
  
  p.shr.max = max(c(res_ibm$profit.shore/1e9, res$summaries$P.shr/1e9))
  p.shr.min = min(c(res_ibm$profit.shore/1e9, res$summaries$P.shr/1e9))
  plot(y=res_ibm$profit.shore/1e9, x=seq(1,nsteps,1), ylab="Profit at shore (Billions NOK)", xlab="Year", col="cyan3", type="l", ylim=c(p.shr.min,p.shr.max))
  points(y=res$summaries$P.shr/1e9, x=res$summaries$year, type="l")
  
  d = pop$get_state()
  d1 = d %>% group_by(age) %>% summarize(mat = length(which(isMature))/length(isMature))
  plot(mat, type="l")
  points(d1$mat~I(d1$age-1), type="o", col="cyan3") # Decrement age to get the right maturation prob (see note above)
  
    plot(res_ibm$r0~seq(1,nsteps,1), xlab="Year", ylab= "r0", col="cyan3", type="p", ylim=c(0,30))
    abline(h=21.77, col="black")

    matplot(y=cbind(res_ibm$survival_mean, res_ibm$maturity, res_ibm$Nrel), x=seq(1,nsteps,1), xlab="Year", ylab= "p_survival / maturity / Nrel", col=c("cyan3", "magenta3", "yellow3"), type="l", lty=1, ylim=c(0,1.2))
    
  matplot(y=cbind(res_ibm$factor_dg, res_ibm$factor_dr), x=seq(1,nsteps,1), xlab="Year", ylab= "dl_ratio, r_ratio", col=c("cyan3", "magenta3"), type="l", lty=1)

  matplot(y=cbind(res_ibm$length90, res_ibm$max_length), x=seq(1,nsteps,1), xlab="Year", ylab= "Length (90 %ile)", col=c("cyan3", "cyan4"), type="l", lty=1)
  
  dist = table(d$age, d$length)
  image(x=as.numeric(rownames(dist)), y = as.numeric(colnames(dist)), z=log(1+3*log(dist)), col=scales::viridis_pal()(100), xlab="Age", ylab="Length")
}
```

```{r fig.height=9}
pop = new(Population, fish)
# Parameters to reproduce Dankel et al results
# pop$par$dsea = 0.09 # tuned value
pop$set_superFishSize(2e6)

nsteps = 200
h = 0.05
lf = 45

pop$verbose = F
res_ibm = sim$simulate(pop, lf, h, nsteps, 1.93e3, 5.61, T)

plot_timeseries(res_ibm, pop, h)
```


### Multiple populations


```{r}
plot_hscan = function(res_ibm_full){
  lf = 45
  arr = res_ibm_full 
  names = c("ssb", "yield", "emp.sea", "emp.shr", 
	                           "profit.sea", "profit.shr", "tsb", 
	                           "r0", "nrecruits", "nsuperfish",
	                           "factor_dg", "factor_dr", "max_length",
                             "length90", "p_survival", "maturity", "Nrel")
  dat_ibm = data.frame(matrix(ncol=length(names), nrow=0))
  colnames(dat_ibm) = names
  dat = data.frame(matrix(ncol=7, nrow=0))
  colnames(dat) = c("ssb", "yield", "emp.sea", "emp.shr", "profit.sea", "profit.shr", "tsb")
  for (ih in 1:length(hvec)){
    res = simulate(hvec[ih], lf, F)
    v = colMeans((res$summaries %>% select(SSB, Y, D.sea, D.shr, P.sea, P.shr, TSB))[151:200,])
    dat[nrow(dat)+1,] = v/c(1e9, 1e9, 1, 1, 1e9, 1e9, 1e9)
    v_ibm = colMeans(arr[151:200, ih, 1, 1,])
    dat_ibm[nrow(dat_ibm)+1,] = v_ibm/c(1e9, 1e9, 1, 1, 1e9, 1e9, 1e9, 1, 1, 1, 1, 1,1,1,1,1,1)
  }
  # dat$employment = dat$emp.sea+dat$emp.shr
  # dat$profit = dat$profit.sea+dat$profit.shr
  
  
  par(mfrow = c(4,3), mar=c(5,5,1,1), cex.lab=1.5, cex.axis=1.5)
  matplot(ylab="ssb (MT)",y=cbind(dat_ibm$ssb, dat$ssb), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="tsb (MT)",y=cbind(dat_ibm$tsb, dat$tsb), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="yield (MT)",y=cbind(dat_ibm$yield, dat$yield), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="employment sea (PY)",y=cbind(dat_ibm$emp.sea, dat$emp.sea), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="employment shore (PY)",y=cbind(dat_ibm$emp.shr, dat$emp.shr), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="profit sea (Bn NOK)",y=cbind(dat_ibm$profit.sea, dat$profit.sea), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="profit shore (Bn NOK)",y=cbind(dat_ibm$profit.shr, dat$profit.shr), x=hvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab="Harvest prop")
  matplot(ylab="Length %iles",y=cbind(dat_ibm$max_length, dat_ibm$length90), x=hvec, type="l", col=c("cyan2", "cyan4"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="dl ratio, r ratio",y=cbind(dat_ibm$factor_dg, dat_ibm$factor_dr), x=hvec, type="l", col=c("cyan3", "magenta3"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="Superfish",y=cbind(dat_ibm$nsuperfish), x=hvec, type="l", col=c("cyan2", "cyan4"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="Survival prob / Maturity",y=cbind(dat_ibm$p_survival, dat_ibm$maturity), x=hvec, type="l", col=c("cyan3", "magenta3"), lwd=1, lty=1, xlab="Harvest prop")
  matplot(ylab="Survival prob / Maturity / Nrel",y=cbind(dat_ibm$p_survival, dat_ibm$maturity, dat_ibm$Nrel), x=hvec, type="l", col=c("cyan3", "magenta3", "yellow3"), lwd=1, lty=1, xlab="Harvest prop")
  }

```

```{r fig.height=9}
# pop$par$dsea = 0.054
hvec = seq(0., 0.7, length.out=100)
res_ibm_full = sim$simulate_multi_2d(pop, c(5.6), lf, hvec, nsteps, 1.93e3, T)

plot_hscan(res_ibm_full)
```

### Temperature scan
```{r}
plot_Tscan = function(res_ibm_full, h){
  lf = 45
  arr = res_ibm_full 
  names = c("ssb", "yield", "emp.sea", "emp.shr", 
	                           "profit.sea", "profit.shr", "tsb", 
	                           "r0", "nrecruits", "nsuperfish",
	                           "factor_dg", "factor_dr", "max_length",
                             "length90", "p_survival", "maturity", "Nrel")
  dat_ibm = data.frame(matrix(ncol=length(names), nrow=0))
  colnames(dat_ibm) = names
  dat = data.frame(matrix(ncol=7, nrow=0))
  colnames(dat) = c("ssb", "yield", "emp.sea", "emp.shr", "profit.sea", "profit.shr", "tsb")
  res = simulate(h, lf, F)
  for (it in 1:length(tvec)){
    v = colMeans((res$summaries %>% select(SSB, Y, D.sea, D.shr, P.sea, P.shr, TSB))[151:200,])
    dat[nrow(dat)+1,] = v/c(1e9, 1e9, 1, 1, 1e9, 1e9, 1e9)
    v_ibm = colMeans(arr[151:200, 1, 1, it,])
    dat_ibm[nrow(dat_ibm)+1,] = v_ibm/c(1e9, 1e9, 1, 1, 1e9, 1e9, 1e9, 1, 1, 1, 1, 1,1,1,1,1,1)
  }
  # dat$employment = dat$emp.sea+dat$emp.shr
  # dat$profit = dat$profit.sea+dat$profit.shr
  
  xvec = tvec
  xlab1 = "SST"
  par(mfrow = c(4,3), mar=c(5,5,1,1), cex.lab=1.5, cex.axis=1.5)
  matplot(ylab="ssb (MT)",y=cbind(dat_ibm$ssb, dat$ssb), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="tsb (MT)",y=cbind(dat_ibm$tsb, dat$tsb), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="yield (MT)",y=cbind(dat_ibm$yield, dat$yield), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="employment sea (PY)",y=cbind(dat_ibm$emp.sea, dat$emp.sea), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="employment shore (PY)",y=cbind(dat_ibm$emp.shr, dat$emp.shr), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="profit sea (Bn NOK)",y=cbind(dat_ibm$profit.sea, dat$profit.sea), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="profit shore (Bn NOK)",y=cbind(dat_ibm$profit.shr, dat$profit.shr), x=xvec, type="l", col=c("cyan2", "black"), lwd=2:1, lty=1, xlab=xlab1)
  matplot(ylab="Length %iles",y=cbind(dat_ibm$max_length, dat_ibm$length90), x=xvec, type="l", col=c("cyan2", "cyan4"), lwd=1, lty=1, xlab=xlab1)
  matplot(ylab="dl ratio, r ratio",y=cbind(dat_ibm$factor_dg, dat_ibm$factor_dr), x=xvec, type="l", col=c("cyan3", "magenta3"), lwd=1, lty=1, xlab=xlab1)
  matplot(ylab="Superfish",y=cbind(dat_ibm$nsuperfish), x=xvec, type="l", col=c("cyan2", "cyan4"), lwd=1, lty=1, xlab=xlab1)
  matplot(ylab="Survival prob / Maturity",y=cbind(dat_ibm$p_survival, dat_ibm$maturity), x=xvec, type="l", col=c("cyan3", "magenta3"), lwd=1, lty=1, xlab=xlab1)
  matplot(ylab="Survival prob / Maturity / Nrel",y=cbind(dat_ibm$p_survival, dat_ibm$maturity, dat_ibm$Nrel), x=xvec, type="l", col=c("cyan3", "magenta3", "yellow3"), lwd=1, lty=1, xlab=xlab1)
  }

```

```{r fig.height=9}
# pop$par$dsea = 0.054
tvec = seq(5.6, 10, length.out=100)
res_ibm_full = sim$simulate_multi_2d(pop, tvec, lf, 0.2, nsteps, 1.93e3, T)

plot_Tscan(res_ibm_full, 0.2)
```