// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rfish.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_fish_module();
RcppExport SEXP _rcpp_module_boot_population_module();
RcppExport SEXP _rcpp_module_boot_simulator_module();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_fish_module", (DL_FUNC) &_rcpp_module_boot_fish_module, 0},
    {"_rcpp_module_boot_population_module", (DL_FUNC) &_rcpp_module_boot_population_module, 0},
    {"_rcpp_module_boot_simulator_module", (DL_FUNC) &_rcpp_module_boot_simulator_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rfish(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
